comment: |
  PR 제목을 기준으로 라벨을 자동 부여했어요. 
  필요할 경우 라벨을 수정하거나 추가해 주세요 🙌
  그럼 오늘도 즐코하세요 - ̗̀ෆ(˶'ᵕ'˶)ෆ  ̖́-

labels:
  '✨ Feature':
    - '^feat: .+'

  '🐞 BugFix':
    - '^fix: .+'

  '📄 Docs':
    - '^docs: .+'

  '🧹 Chore':
    - '^chore: .+'

  '🪄 Modify':
    - '^modify: .+'

  '🎨 UI':
    - '^style: .+'

  '❄️ Release':
    - '^merge: .+'

  '🛠️ Refactor':
    - '^refactor: .+'

  '🧪 Test':
    - '^test: .+'
