// This file is generated by scripts/generate-exports.mjs.
// Do not edit manually.

export { default as IllustrationBellEmpty } from './il-bell-empty.svg';
export { default as IllustrationBooksCap } from './il-books-cap.svg';
export { default as IllustrationBoxStarsCircle } from './il-box-stars-circle.svg';
export { default as IllustrationBoxStarsOpen } from './il-box-stars-open.svg';
export { default as IllustrationCalendarEmpty } from './il-calendar-empty.svg';
export { default as IllustrationClipboardSearch } from './il-clipboard-search.svg';
export { default as IllustrationCommentEmpty } from './il-comment-empty.svg';
export { default as IllustrationDefaultProfile } from './il-default-profile.svg';
export { default as IllustrationEmailCheck } from './il-email-check.svg';
export { default as IllustrationFlag } from './il-flag.svg';
export { default as IllustrationFolderSearch } from './il-folder-search.svg';
export { default as IllustrationHallOfFame } from './il-hall-of-fame.svg';
export { default as IllustrationIceCupBowl } from './il-ice-cup-bowl.svg';
export { default as IllustrationLogoAboutSnoroseCloud } from './il-logo-about-snorose-cloud.svg';
export { default as IllustrationLogoSnoroseCloud } from './il-logo-snorose-cloud.svg';
export { default as IllustrationLogoSnorose } from './il-logo-snorose.svg';
export { default as IllustrationMicrophone } from './il-microphone.svg';
export { default as IllustrationNoSales } from './il-no-sales.svg';
export { default as IllustrationNoTicketTransfer } from './il-no-ticket-transfer.svg';
export { default as IllustrationNotFound } from './il-not-found.svg';
export { default as IllustrationPadlock } from './il-padlock.svg';
export { default as IllustrationPostEmpty } from './il-post-empty.svg';
export { default as IllustrationResidence } from './il-residence.svg';
export { default as IllustrationScrapPostEmpty } from './il-scrap-post-empty.svg';
export { default as IllustrationSnowGroundCircle } from './il-snow-ground-circle.svg';
export { default as IllustrationSnowGround } from './il-snow-ground.svg';
export { default as IllustrationSnowMountainCircle } from './il-snow-mountain-circle.svg';
export { default as IllustrationSnowMountain } from './il-snow-mountain.svg';
export { default as IllustrationSnowfallCircle } from './il-snowfall-circle.svg';
export { default as IllustrationSnowfall } from './il-snowfall.svg';
export { default as IllustrationStarHonorBoard } from './il-star-honor-board.svg';
export { default as IllustrationTaskComplete } from './il-task-complete.svg';
export { default as IllustrationTaskFailed } from './il-task-failed.svg';
export { default as IllustrationTrashcanCircle } from './il-trashcan-circle.svg';
