import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);

const generatedHeader =
  '// This file is generated by scripts/generate-exports.mjs.\n' +
  '// Do not edit manually.\n\n';

await generateExport({
  output: 'src/icons/index.ts',
  groups: [
    {
      sourceDir: 'src/icons/basic',
      filePrefix: 'ic-basic-',
      exportPrefix: 'Icon',
    },
    {
      sourceDir: 'src/icons/multi',
      filePrefix: 'ic-multi-',
      exportPrefix: 'IconMulti',
    },
  ],
});

await generateExport({
  output: 'src/illustrations/index.ts',
  groups: [
    {
      sourceDir: 'src/illustrations',
      filePrefix: 'il-',
      exportPrefix: 'Illustration',
    },
  ],
});

async function generateExport({ output, groups }) {
  const outputPath = path.join(rootDir, output);
  const outputDir = path.dirname(outputPath);
  const exportGroups = [];
  let exportCount = 0;

  for (const group of groups) {
    const sourceDir = path.join(rootDir, group.sourceDir);
    const records = (await listSvgFiles(sourceDir)).map((filePath) => ({
      exportName: getExportName(filePath, group),
      importPath: `./${toPosixPath(path.relative(outputDir, filePath))}`,
    }));

    exportCount += records.length;

    const exportGroup = records
      .map(
        ({ exportName, importPath }) =>
          `export { default as ${exportName} } from '${importPath}';`,
      )
      .join('\n');

    exportGroups.push(exportGroup);
  }

  await writeFile(
    outputPath,
    `${generatedHeader}${exportGroups.filter(Boolean).join('\n\n')}\n`,
  );

  console.log(`Generated ${output} (${exportCount} exports)`);
}

async function listSvgFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const entryPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await listSvgFiles(entryPath)));
    } else if (entry.isFile() && entry.name.endsWith('.svg')) {
      files.push(entryPath);
    }
  }

  return files.sort((a, b) =>
    toPosixPath(path.relative(rootDir, a)).localeCompare(
      toPosixPath(path.relative(rootDir, b)),
    ),
  );
}

function getExportName(filePath, group) {
  const fileName = path.basename(filePath, '.svg');

  if (!fileName.startsWith(group.filePrefix)) {
    const relativePath = toPosixPath(path.relative(rootDir, filePath));

    throw new Error(
      `${relativePath} must start with "${group.filePrefix}" to generate an export name.`,
    );
  }

  const name = fileName
    .replace(group.filePrefix, '')
    .split('-')
    .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
    .join('');

  return `${group.exportPrefix}${name}`;
}

function toPosixPath(filePath) {
  return filePath.split(path.sep).join('/');
}
